# -*- coding: utf-8 -*-
"""task_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nu_fkRwYeGajtgi3WTSmMor1ONr_NDhn

**Importing required libraries**
"""

import requests
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

"""**Importing the data**"""

url = 'https://raw.githubusercontent.com/AdiPersonalWorks/Random/master/student_scores%20-%20student_scores.csv'
res = requests.get(url, allow_redirects=True)
with open('student_scores.csv','wb') as file:
    file.write(res.content)

student_scores = pd.read_csv('student_scores.csv')

"""**looking into the data**"""

print(student_scores.head())

"""**Input and Output**"""

X = student_scores.iloc[:,0:1].values


y = student_scores.iloc[:,1].values

"""**Visualising the data**"""

plt.scatter(X,y)
plt.xlabel('study hours')
plt.ylabel('percentage scored')
plt.title('percentage scored vs study hours')
plt.show()

"""**Fitting the model**"""

model = LinearRegression()
Xtrain, Xtest, ytrain , ytest = train_test_split(X,y,test_size=0.20,random_state = 0)
model.fit(Xtrain,ytrain)

"""**Checking for accuracy**"""

print('model accuracy score :' , model.score(Xtest,ytest))

"""**coefficients of the fitted linear regression model**"""

print('model coefficients :',model.coef_)

"""**Predicting the scores using the trained model**"""

y_ = model.predict(X)

"""**y_actual vs y_predicted**"""

print('y_actual vs y_predicted')
print('')
for i in range(len(y))  :
  print(y[i],y_[i])

"""**Visualization the output**"""

plt.scatter(X,y)
plt.plot(X,y_,color = 'red')
plt.show()

"""**score if a student studies for 9.25 hrs/ day, so x = 9.25**"""

#score if a student studies for 9.25 hrs/ day, so x = 9.25
#y = m*x + c

ypred = model.coef_*9.25 + model.intercept_
print('score if a student studies for 9.25 hrs/ day : ', ypred)